




CREATE TABLE NewClass5 (
 primaryKey UUID NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 Editor VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE NewClass6 (
 primaryKey UUID NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 Editor VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE NewClass7 (
 primaryKey UUID NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 Editor VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE NewClass1 (
 primaryKey UUID NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 Editor VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE NewClass2 (
 primaryKey UUID NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 Editor VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 NewClass1 UUID NOT NULL,
 NewClass4 UUID NOT NULL,
 NewClass5 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE NewClass3 (
 primaryKey UUID NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 Editor VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 NewClass5 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE NewClass4 (
 primaryKey UUID NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 Editor VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE NewClass2 ADD CONSTRAINT FK57891fa661cfff750b33a525591d034b0f7c0bc4 FOREIGN KEY (NewClass1) REFERENCES NewClass1; 
CREATE INDEX Index57891fa661cfff750b33a525591d034b0f7c0bc4 on NewClass2 (NewClass1); 

 ALTER TABLE NewClass2 ADD CONSTRAINT FK1154fa6e64f722c57a08ebadb51d90bca58ce225 FOREIGN KEY (NewClass4) REFERENCES NewClass4; 
CREATE INDEX Index1154fa6e64f722c57a08ebadb51d90bca58ce225 on NewClass2 (NewClass4); 

 ALTER TABLE NewClass2 ADD CONSTRAINT FK0afe49704a9ded7f366508d16ed2349f79c33de7 FOREIGN KEY (NewClass5) REFERENCES NewClass5; 
CREATE INDEX Index0afe49704a9ded7f366508d16ed2349f79c33de7 on NewClass2 (NewClass5); 

 ALTER TABLE NewClass3 ADD CONSTRAINT FK10a6ff4e52c4046a1cce03723152159a7d40071e FOREIGN KEY (NewClass5) REFERENCES NewClass5; 
CREATE INDEX Index10a6ff4e52c4046a1cce03723152159a7d40071e on NewClass3 (NewClass5); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

