//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test11
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class3.
    /// </summary>
    // *** Start programmer edit section *** (NewClass3 CustomAttributes)

    // *** End programmer edit section *** (NewClass3 CustomAttributes)
    [AutoAltered()]
    [Caption("New class3")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "NewClass5 as \'New class5\'"})]
    [View("NewClass3E", new string[] {
            "NewClass5 as \'New class5\'"})]
    [MasterViewDefineAttribute("NewClass3E", "NewClass5", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("NewClass3L", new string[0])]
    public class NewClass3 : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {

        private System.Nullable<System.DateTime> fCreateTime;

        private string fCreator;

        private string fEditor;

        private System.Nullable<System.DateTime> fEditTime;

        private IIS.Test11.NewClass5 fNewClass5;

        // *** Start programmer edit section *** (NewClass3 CustomMembers)

        // *** End programmer edit section *** (NewClass3 CustomMembers)


        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.CreateTime CustomAttributes)

        // *** End programmer edit section *** (NewClass3.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.CreateTime Get start)

                // *** End programmer edit section *** (NewClass3.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (NewClass3.CreateTime Get end)

                // *** End programmer edit section *** (NewClass3.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.CreateTime Set start)

                // *** End programmer edit section *** (NewClass3.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (NewClass3.CreateTime Set end)

                // *** End programmer edit section *** (NewClass3.CreateTime Set end)
            }
        }

        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.Creator CustomAttributes)

        // *** End programmer edit section *** (NewClass3.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.Creator Get start)

                // *** End programmer edit section *** (NewClass3.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (NewClass3.Creator Get end)

                // *** End programmer edit section *** (NewClass3.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.Creator Set start)

                // *** End programmer edit section *** (NewClass3.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (NewClass3.Creator Set end)

                // *** End programmer edit section *** (NewClass3.Creator Set end)
            }
        }

        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.Editor CustomAttributes)

        // *** End programmer edit section *** (NewClass3.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.Editor Get start)

                // *** End programmer edit section *** (NewClass3.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (NewClass3.Editor Get end)

                // *** End programmer edit section *** (NewClass3.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.Editor Set start)

                // *** End programmer edit section *** (NewClass3.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (NewClass3.Editor Set end)

                // *** End programmer edit section *** (NewClass3.Editor Set end)
            }
        }

        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.EditTime CustomAttributes)

        // *** End programmer edit section *** (NewClass3.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.EditTime Get start)

                // *** End programmer edit section *** (NewClass3.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (NewClass3.EditTime Get end)

                // *** End programmer edit section *** (NewClass3.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.EditTime Set start)

                // *** End programmer edit section *** (NewClass3.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (NewClass3.EditTime Set end)

                // *** End programmer edit section *** (NewClass3.EditTime Set end)
            }
        }

        /// <summary>
        /// New class3.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.NewClass5 CustomAttributes)

        // *** End programmer edit section *** (NewClass3.NewClass5 CustomAttributes)
        [PropertyStorage(new string[] {
                "NewClass5"})]
        [NotNull()]
        public virtual IIS.Test11.NewClass5 NewClass5
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.NewClass5 Get start)

                // *** End programmer edit section *** (NewClass3.NewClass5 Get start)
                IIS.Test11.NewClass5 result = this.fNewClass5;
                // *** Start programmer edit section *** (NewClass3.NewClass5 Get end)

                // *** End programmer edit section *** (NewClass3.NewClass5 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.NewClass5 Set start)

                // *** End programmer edit section *** (NewClass3.NewClass5 Set start)
                this.fNewClass5 = value;
                // *** Start programmer edit section *** (NewClass3.NewClass5 Set end)

                // *** End programmer edit section *** (NewClass3.NewClass5 Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Test11.NewClass3));
                }
            }

            /// <summary>
            /// "NewClass3E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass3E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass3E", typeof(IIS.Test11.NewClass3));
                }
            }

            /// <summary>
            /// "NewClass3L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass3L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass3L", typeof(IIS.Test11.NewClass3));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}

