//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test11
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NewClass9.
    /// </summary>
    // *** Start programmer edit section *** (NewClass9 CustomAttributes)

    // *** End programmer edit section *** (NewClass9 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class NewClass9 : IIS.Test11.NewClass8
    {

        private IIS.Test11.DetailArrayOfNewClass10 fNewClass10;

        // *** Start programmer edit section *** (NewClass9 CustomMembers)

        // *** End programmer edit section *** (NewClass9 CustomMembers)


        /// <summary>
        /// NewClass9.
        /// </summary>
        // *** Start programmer edit section *** (NewClass9.NewClass10 CustomAttributes)

        // *** End programmer edit section *** (NewClass9.NewClass10 CustomAttributes)
        public virtual IIS.Test11.DetailArrayOfNewClass10 NewClass10
        {
            get
            {
                // *** Start programmer edit section *** (NewClass9.NewClass10 Get start)

                // *** End programmer edit section *** (NewClass9.NewClass10 Get start)
                if ((this.fNewClass10 == null))
                {
                    this.fNewClass10 = new IIS.Test11.DetailArrayOfNewClass10(this);
                }
                IIS.Test11.DetailArrayOfNewClass10 result = this.fNewClass10;
                // *** Start programmer edit section *** (NewClass9.NewClass10 Get end)

                // *** End programmer edit section *** (NewClass9.NewClass10 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass9.NewClass10 Set start)

                // *** End programmer edit section *** (NewClass9.NewClass10 Set start)
                this.fNewClass10 = value;
                // *** Start programmer edit section *** (NewClass9.NewClass10 Set end)

                // *** End programmer edit section *** (NewClass9.NewClass10 Set end)
            }
        }
    }
}

