//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test11
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NewClass8.
    /// </summary>
    // *** Start programmer edit section *** (NewClass8 CustomAttributes)

    // *** End programmer edit section *** (NewClass8 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class NewClass8 : ICSSoft.STORMNET.DataObject
    {

        // *** Start programmer edit section *** (NewClass8 CustomMembers)

        // *** End programmer edit section *** (NewClass8 CustomMembers)

    }
}

